version: "3"
services:
  server:
    container_name: newtrition-server
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    links:
      - database
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://database:27017/newtrition
      PORT: 4000
      WAIT_HOSTS: database:27017
    networks:
      - net-newtrition-backend
  database:
    container_name: database
    image: mongo
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=newtrition
    networks:
      - net-newtrition-backend
networks:
  net-newtrition-backend:
    driver: bridge
